// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // SQLite for local dev (feature 002-url-shortener). For production use DATABASE_URL (e.g. Turso).
    url: process.env["DATABASE_URL"]?.startsWith("file:")
      ? process.env["DATABASE_URL"]
      : "file:./prisma/dev.db",
  },
});
